### ISSUE TITLE
jail release point?

### ISSUE THREAD

**Issue by VirtualGaming1** [Caltinor/SimpleJail#1]
just came across this serverside mod and wondering if you can set a command for where you set release point for the jail that they were sent too. this would be great if there is multi jail in the server like different faction

**Comment by VirtualGaming1** [comment]
No presser because the server I'm trying to get going with my modpack is player build spawn and city and player run factions and hoping have player run economy as well and it is at the starting stage still

**Comment by Caltinor** [comment]
This was implemented with https://github.com/Caltinor/SimpleJail/commit/d37824ff66ec8802c6f103cf3870acacd8c53648
just forgot to close this issue
