### ISSUE TITLE
Mod prevents me from using command blocks.

### ISSUE THREAD

**Issue by zderApfel** [Caltinor/SimpleJail#2]
Hello, whenever I try to use command blocks I get this message in the block: `A player is required to run this command here`

And this command in the console 

```
[27.06 21:11:49] [Server] Index1
[27.06 21:11:49] [Server] Listeners:
[27.06 21:11:49] [Server] NORMAL
[27.06 21:11:49] [Server] ASM: class com.dicemc.dicemcsjm.EventHandler onCommand(Lnet/minecraftforge/event/CommandEvent;)V
[27.06 21:11:49] [Server] com.mojang.brigadier.exceptions.CommandSyntaxExceptionA player is required to run this command here
```

I figured out if was this mod because your name (DiceMC) is in the error message. Do you have any suggestion as to how I can fix this?

**Comment by Caltinor** [comment]
I can look into this.  Could you please provide the entire log?

**Comment by zderApfel** [comment]
Certainly, here's the log file ->
[2021-06-27-1.log](https://github.com/Caltinor/SimpleJail/files/6727318/2021-06-27-1.log)

This happens when I try any command, so far I've tried `say`, `tellraw`, and `execute`

**Comment by Caltinor** [comment]
[SimpleJail-1.16--1.1.3.zip](https://github.com/Caltinor/SimpleJail/files/6727421/SimpleJail-1.16--1.1.3.zip)
Try this file.  It should resolve your issue.  Once you confirm this works with your pack, I will push this to CF so it can be included in packs.

**Comment by zderApfel** [comment]
So I jailed myself to test it, but now `/release` isn't working, and it's been far past the minute I put down to jail me for.

**Comment by Caltinor** [comment]
can you release yourself from the console or is this a singleplayer instance?

**Comment by zderApfel** [comment]
> can you release yourself from the console or is this a singleplayer instance?

I tried from the console and nothing happened

**Comment by Caltinor** [comment]
is it telling you you cannot perform the command or just nothing happens when you run it?

**Comment by zderApfel** [comment]
The latter, nothing happens

**Comment by Caltinor** [comment]
are you using anything that skips ticks like performant?  even so, unless you were constantly skipping the same tick over and over it would attempt to release you once every 10 seconds.

**Comment by zderApfel** [comment]
Nope, not doing anything like that

**Comment by zderApfel** [comment]
Also no I wasn't getting any error codes in the console either

**Comment by Caltinor** [comment]
okay.  i'll look into this more.  I just did a test and I wasn't being TP'd back to the jail like I should have been too.

**Comment by zderApfel** [comment]
Thank you for your help! I appreciate the prompt response times. The mod isn't vital to my server so please don't feel rushed.

I do have a slightly off-topic question though, does this mod need to be installed both client and server side or only server side?

**Comment by Caltinor** [comment]
it works serverside, but you'll want to provide the clients with a resource pack containing the translations if you want the chat messages to make sense for them.

**Comment by Caltinor** [comment]
[SimpleJail-1.16--1.1.3.zip](https://github.com/Caltinor/SimpleJail/files/6737151/SimpleJail-1.16--1.1.3.zip)
@zderApfel this should work.  this took a little longer because I found the entire dimension-based jail handing was completely broken so I fixed that too.  let me know if this works properly for you.

**Comment by zderApfel** [comment]
It's working as intended, except that mod messages are coming up like this: 
![image](https://user-images.githubusercontent.com/67031028/123981600-681a3c80-d990-11eb-98b9-5a4cfe4489a2.png)

**Comment by Caltinor** [comment]
if using a vanilla client, do you have a resource pack with the lang entries?  if using modded client, do you have the mod on the client or the resource pack?

**Comment by zderApfel** [comment]
> if using a vanilla client, do you have a resource pack with the lang entries? if using modded client, do you have the mod on the client or the resource pack?

Oh right, I forgot to put it on my client! Sorry about that

**Comment by Caltinor** [comment]
you don't have to, but like I said, you need the lang entries in a resource pack at a minimum.  you can get the lang file from this repo if you need the entries.

Since it's working I am going to close this issue.  Thank you for the report.
