### ISSUE TITLE
Jailed players are released when server restarts, regardless of length of "sentence"

### ISSUE THREAD

**Issue by bauerbach** [Caltinor/SimpleJail#4]
If I restart my server when a player is jailed, that player is no longer considered jailed and can break out if in Creative or Survival mode.

**Comment by Caltinor** [comment]
I am unable to reproduce this issue.  Here is what I did:
1. start a modded server with SimpleJail
2. Join with a vanilla client
3. Detain the player for 2000 minutes in a jail with a leash of 10
4. Attempts to leave the area result in being teleported back as expected.
5. shut down the server completely
6. start the server
7. rejoin with vanilla client.
8. attempt to leave the area and see I am still detained.
